### PR TITLE
SCPU: fix dma registers space

### PR DESCRIPTION
**Pull request by srg320**
fix world map sequences in Illusion of Gaia

### CODE REVIEW

**Comment by paulb-nl** [comment]
I noticed $43xF is not supported? Fullsnes says it is:

> 43xFh - MIRRx - Read/Write-able mirror of 43xBh (R/W)
> Mirror of 43xBh.

**Comment by James-F2** [comment]
Source: https://wiki.superfamicom.org/registers
> The effects of these registers (if any) are unknown. $43xf and $43xb are really aliases for the same register. This register is set to $ff on power on, and is unchanged on reset.

Do you think a game might check this register?

**Comment by paulb-nl** [comment]
Doesn't really matter if  games use it or not. The SNES hardware supports it and it can be used as storage so anything could use it. (43xB/F)

> 43xBh - UNUSEDx - Unused Byte (R/W)
>   7-0   Not used (read/write-able)
> Can be used as a fast RAM location (but NOT as a fixed DMA source address for memfill). Storing any value in this register seems to have no effect on the transfer (and the value is left intact, not modified by DMA nor direct nor indirect HDMAs).

**Comment by srg320** [comment]
There are games that use $43xB, but i don't know games that use $43xF.

**Comment by paulb-nl** [comment]
You never know when something will use it. It is a minor change for hardware accuracy.

**Comment by srg320** [comment]
@paulb-nl 
Absolutely agree with you.

**Comment by James-F2** [comment]
Doing some reading, I don't think filling the WRAM with with FF is good.
The real console has the RAM at random on boot.
This does have an effect on some games AI, unlike the Backup Ram on the cartridge.

Reading :
https://octolinker-demo.now.sh/TASVideos/BizHawk/issues/1701
https://github.com/snes9xgit/snes9x/issues/299

**Comment by paulb-nl** [comment]
Looks like real consoles alternate between certain patterns. 

Higan fills 4 bytes with a number and then invert the bits and fills another 4 bytes and so on. Sometimes it fills 8 bytes then inverts.

Example:
> 86 86 86 86 79 79 79 79 86 86 86 86 79 79 79 79

[http://tasvideos.org/forum/viewtopic.php?p=488318&sid=982b6924668a4973ed4dba01a32f8635#488318](http://tasvideos.org/forum/viewtopic.php?p=488318&sid=982b6924668a4973ed4dba01a32f8635#488318)
VoExehZ

**Comment by sorgelig** [comment]
i think checkers is most common ram content on a real HW. 
It's not hard to implement.

**Comment by James-F2** [comment]
mrehkopf (ikari_01)  posted whet the sd2snes.
https://github.com/MiSTer-devel/SNES_MiSTer/issues/187#issuecomment-573376383

Should be very useful.

**Comment by paulb-nl** [comment]
We could have a counter running from 00-FF and then latch the value when a rom load starts and use it for the pattern.

**Comment by James-F2** [comment]
So it will start counting when core boots and stop counting on first rom load,, then fill WRAM higan-style.
An elegant solution, I like it.

**Pull request merged**
