### PR TITLE
sys: Csync: Shift Hsync left by 1 Hsync period during Vsync

### PR DESCRIPTION
**Pull request by paulb-nl**
Otherwise there is a missing Hsync at the end of Vsync.

I don't know if this should be handled in sys or the core should generate Csync. Every core should have Csync like this. Vsync needs to be aligned to Hsync.

This is a comparison between MiSTer and a real SNES:
mister_csync_snes

### CODE REVIEW

**Comment by sorgelig** [comment]
It needs to be tested with direct video. It's very sensitive to vsync aligned to hsync in the start. Even one pixel of misaligning breaks the direct video. Not sure if that ending of vsync with separated hsync will work good.

**Comment by sorgelig** [comment]
Why we need it btw?

**Comment by sorgelig** [comment]
by the way, there are interlace field. How it will be handled by your module?

**Comment by sorgelig** [comment]
One more thought - i think it's not HSync should be shifted. It's VSync should be shortened to 1 HSync size. Otherwise first line will be shorter.

**Comment by James-F2** [comment]
This is my measurements of Paul's code.
I verified it works with both IO board VGA output, and direct_video=1 with HDMI to VGA converter, which look like the 'after' measurement.
Interlaced signal works with both too.

I think Paul mentioned in our PMs that the OSSC was losing sync with one of the last builds were you changed the VSync position.

**Comment by paulb-nl** [comment]
Yes OSSC is one of the devices that has issues with the missing HSync.
>One more thought - i think it's not HSync should be shifted. It's VSync should be shortened to 1 HSync size. Otherwise first line will be shorter.

> So, basically in PPU just need to shorten the VSync on the last line. sys_top will XOR HSync with shortened VSync and you will get the same waveform as on real SNES. (scandoubled video will still have old waveform i think)

The first line in Vsync is not shorter because Csync goes low earlier because the first Hsync is skipped. You can't shorten Vsync because the last Vsync pulse would be shorter then the rest. It would be a mixture of the waveforms. Shorter Vsync in PPU will also affect HDMI Vsync and RGBHV.

An alternative is generating Csync in the PPU itself. It would just be HSYNC_START = HSYNC_START - LENGTH during Vsync in PPU.

**Comment by paulb-nl** [comment]
@James-F2 Here is a Genesis build if you would like to test it: [https://drive.google.com/file/d/1ew53XuQ5hkYxN-hb9uj8E7tYY9wV8OvO/view?usp=sharing](url)

**Comment by James-F2** [comment]
Everything works except 256x224 (240p test suite), which doesn't sync with direct_video=1.

**Comment by paulb-nl** [comment]
Strange, I would have expected 320x224 not to work. 256x224 should be the same as SNES. Can you measure the Vsync?

**Comment by James-F2** [comment]
!! There is no Sync at all (flat line) with your CSync build in 256x224 pattern.

320x224 IO BOARD
320x224 direct_video VGA
256x224 IO BOARD
256x224 direct_video, official build

**Comment by paulb-nl** [comment]
Haha, well I am surprised sync is working at all. It is completely wrong. 6 Hsyncs during Vsync!

**Comment by James-F2** [comment]
https://www.hdretrovision.com/blog/2018/10/22/engineering-csync-part-1-setting-the-stage
According to this page, it looks like the "double pulse" csync (type C), that's why it works.

**Comment by James-F2** [comment]
@paulb-nl 
Obviously you are doing something very right.

320x224 Genesis
256x224 Genesis

**Comment by paulb-nl** [comment]
Ok so the real Genesis uses Csync type C with double pulses but the Genesis core is outputting normal pulses like on your 256x224 official build measurement. My code should not be adding extra Hsyncs.

**Comment by James-F2** [comment]
Your CSync test build looks very close to the real genesis.

**Comment by James-F2** [comment]
No, it just has 6 scanlines of vsync. It uses type B.

**Comment by James-F2** [comment]
@paulb-nl 
Yes, you're right, the genesis does have double pulses (type C).
It has double rate hsync pre-pulses,, then vsync,, then double rate post pulses.

Genesis

**Comment by paulb-nl** [comment]
I think I found the issue. I thought the Genesis core used a video clock of 53.6MHz but it is double that at 107.3MHz so the counters were overflowing. I updated the build in the link above.

**Comment by James-F2** [comment]
Everything works now.

**Comment by sorgelig** [comment]
I still think that VSync in the last line must be shorter, so you won't need to count the pixels. I don't think any device will be affected by shorter VSync in the last line. Usually devices react on beginning of VSync.

Adding that module wich counting the pulse length will bring problems if some core doesn't strictly follow the rules. And there are many such cores.
Almost none of cores have aligned VSync to HSync, for example.

**Comment by paulb-nl** [comment]
Instead of changing the core to make the Vsync shorter, I think its better to change the core to output Csync. We can add a VGA_CS output to the emu module and something like VGA_CS_SEL to choose between Core Csync or Sys simple XOR or Sys Csync generation.

If the core is not ready just set simple XOR. The vga scaler can probably always use Sys Csync generation.

Shifting Hsync is how it is done by every hardware with Csync. Devices react to falling edge of Hsync and the distance between the falling edges of 2 Hsync's is always the same when shifted. Just check the amount of pixels between the falling edges in the scope measurement.

Actually making Vsync shorter makes the distance between falling edges of last Hsync in Vsync shorter than all others.

**Comment by sorgelig** [comment]
I don't like to make the think over-complicated. Requiring for additional CSync from the core is something i would like to avoid.
Do you have any link where i can read that first HSync must be shifted? I really doubt 30 years old HW really did such shift as it would be very expensive to do. It's rather HW shortened the VSync so last HSync could stand off the VSync.

**Comment by sorgelig** [comment]
I think there is an issue in XOR which actually should not be just XOR. First HSync in VSync after XOR simply shifts the VSync for HSync distance. So we need to shift VSync rather than HSync.

**Comment by paulb-nl** [comment]
JamesF posted a lot of scope measurements of real Genesis and SNES here. Both consoles show Hsync is shifted left during VSync so that every Hsync period is the same. 

With the current code in the pull request the result is exactly like the real hardware. Shift Vsync or shorter Vsync won't be the same result.

Ok If you don't want Csync from the core we can just put Csync generation in Sys and have an enable signal to switch to new Csync generation so we can turn it on per core after it is tested?

**Comment by sorgelig** [comment]
this module doing what i've tried to say:
```
module CSync
(
	input      clk,
	input      hsync,
	input      vsync,
	output reg csync
);

always @(posedge clk) begin
	reg old_hs;
	reg [31:0] cnt, cnt_cs, line_sz;

	cnt_cs <= cnt_cs + 1;
	if(cnt_cs >= line_sz) csync <= 1;

	cnt <= cnt + 1;
	old_hs <= hsync;
	if(old_hs ^ hsync) begin
		cnt <= 0;
		if(hsync) begin
			line_sz <= cnt;
			csync <= 0;
			cnt_cs <= 0;
		end
		else if(~vsync) csync <= 1;
	end
end

endmodule
```


it doesn't shift the hsync.
Though, module needs to be tweaked a little for interlace.

But what i was afraid is true: direct video doesn't like this csync. Probably VGA converter doesn't like it.

**Comment by James-F2** [comment]
Sorry to interrupt, I have tested all Paul's CSync builds with Direct Video and HDMI->VGA adapter and everything was working properly.

**Comment by paulb-nl** [comment]
> it doesn't shift the HSync, so all HSync distances are the same.

Did you measure all Hsync falling edge to falling edge? If you don't shift Hsync it is impossible that falling edge to falling edge of Hsync outside and inside Vsync will be the same. 

Hsync is inverted in Vsync! This makes the falling edge shift to the right. So it needs to be shifted left to make the falling edges align again.

That is probably why it does not work on Direct video and mine does.

**Comment by sorgelig** [comment]
I will re-check it and try your version in direct video.

**Pull request merged**
