### PR TITLE
Option to select initial WRAM content

### PR DESCRIPTION
**Pull request by paulb-nl**

### CODE REVIEW

**Comment by sorgelig** [comment]
That means even on real SNES some games/demos don't work?

**Comment by paulb-nl** [comment]
These RAM patterns are seen on real SNES consoles so if a demo doesn't work with a certain pattern then it shouldn't work on some SNES consoles too. 

The demos in the past were made to be run on floppy copiers. Maybe they worked properly in the past if they always read from memory where the copier was writing. But then it would depend on the copier.

The game Power Drive was found to have glitches when RAM was filled with zeroes so depending on the RAM chip in your console it might show glitches if RAM has a 0 where the game reads from.

**Comment by sorgelig** [comment]
But i think emulate the emulator is kind of weird.. i mean SD2SNES which is definitely not the official SNES HW.

**Comment by sorgelig** [comment]
I think it's better to hide this option from user and use autodetection of problematic games by header. 
Choose most common way to fill the RAM and when problematic game/demo is detected while loading, the RAM will be overwritten with compatible content.
Otherwise it's too cryptic non-friendly option.

**Comment by paulb-nl** [comment]
0x55 SD2SNES option can be renamed to SNES3 because according to the chart it also appears on some original consoles. https://github.com/MiSTer-devel/SNES_MiSTer/pull/188#issuecomment-573359741

The 0xFF option can be removed if you don't want it.

I don't like autodetection at all. There are always roms that are not included in autodetection and people should be able to test non-working roms with the different RAM content. 

If people don't understand it then an explanation in the readme can be added.

**Comment by sorgelig** [comment]
If there are many such non-standard ROMs then it means default RAM fill is wrong.
Real HW has no choice at all and all games supposed to work. Generally speaking adding such option is just encouraging for more crappy programming in mods/hacks.

I imagine if some new super-cool-nad-buggy-mod game doesn't work then user has to try N-different options to find the working config. This is not good.

**Comment by paulb-nl** [comment]
Probably many old demos/hacks are very buggy and won't work with one RAM fill. Then we have to add every broken rom to a list instead of letting the user just change the RAM fill option.

If a new buggy game does not work with the default RAM fill then what? The user will see it does not work and thus will say MiSTer SNES core is bad.

Then you want to add the new game to a list and the user has to wait for a new core release before the game will work? That is also bad.

If you want a list then it's better to have Initial WRAM default to "Auto" and have the 3 RAM fill options as override.

**Pull request merged**
