### PR TITLE
DSP area optimization

### PR DESCRIPTION
**Pull request by gyurco**
BRR_BUF and GTBL moved to BRAM: 40% size decrease with the expense of only 2 BRAM blocks.
Probably you can wait with the merge until it's tested by more than one people (me).

### CODE REVIEW

**Comment by James-F2** [comment]
We will test that on discord.
Killer Instinct had problems with audio and freezing before a fundamental DSP fix by srg320 a few months ago.

**Comment by sorgelig** [comment]
> 
> 
> We will test that on discord.
> Killer Instinct had problems with audio and freezing before a fundamental DSP fix by srg320 a few months ago.

I will wait for your results then.

**Comment by James-F2** [comment]
I played through Killer Instinct with not issues at all.
Maybe we should wait at  least a day since the majority of people are from the west.

**Comment by James-F2** [comment]
I think it's solid.

**Comment by MP2E** [comment]
I agree. I tested a few games that byuu stated require cycle accurate timings for DSP and heard no issues

**Pull request merged**
