### PR TITLE
PPU: Hires subscreen color math should use the previous MAIN_COLOR

### PR DESCRIPTION
**Pull request by paulb-nl**
Fixes Hires text in Marvelous

### CODE REVIEW

**Comment by James-F2** [comment]
That also added a small halo on the right side of the letter selection box that should not be there.

**Comment by paulb-nl** [comment]
@James-F2  Please try out this change https://github.com/paulb-nl/SNES_MiSTer/commit/c482fa01cc643d26f0331d6aa72ce2bb1fafc59d

**Comment by MP2E** [comment]
I tested out the change listed and it does remove the small 'halo' effect, but 2 things still seem a bit off:

https://imgur.com/a/FkpWghE

**Comment by James-F2** [comment]
This is how it looks on the real console+OSSC too.
Yep, that fixed it.

**Comment by paulb-nl** [comment]
Does the right side of the letter S on the Marvelous logo have a shadow on the entire edge on real console or is it like Bsnes where only parts of the letter has a shadow?

**Comment by James-F2** [comment]
Console+OSSC is exactly like Bsnes, pixel for pixel.

**Comment by MP2E** [comment]
Only parts of the letter have a shadow, here is a picture of how it looks on my SNES via OSSC

https://imgur.com/a/bp8bcko

(Camera because my SNES doesn't play nice with the cap card)

Also James-F2 is right, the text is correct. It looks exactly like my SNES, apologies for the confusion.

**Comment by paulb-nl** [comment]
I reworked and simplified color math and I have it pixel perfect now. Now it does color math every half cycle instead of both main and sub on the same cycle. Please test this SNES.rbf https://drive.google.com/file/d/1WYTux3-MJmTwz0VNl6qZBQfG7kwTnxbY/view?usp=sharing

Interestingly Pseudo hires Blend off in Jurrassic Park has a different result now (half pixel offset with green line on the right) but that matches Bsnes. I wonder if it's the same on a real console?

**Comment by James-F2** [comment]
Yep, exactly like real console.
Green line on the right, half pixel gone on the left.

**Comment by sorgelig** [comment]
so c482fa0 commit is needed to fix the issue?

**Comment by paulb-nl** [comment]
@sorgelig no that commit is not needed anymore. I will send a pull request with other changes.

**Comment by MP2E** [comment]
Just tried the RBF posted, it works perfectly! No issues to report that I have found.

**Pull request merged**
