### PR TITLE
Menu order and name fixes.

### PR DESCRIPTION
**Pull request by James-F2**
Menu fixes:
- Rearrange menu order.
- Capital Letters typo fixes.
- Speed Hacks moved to bottom and renamed to Normal/Turbo.
- Pseudo Transparency - Off / Blend.
People did not know that "Stripes" is actually "Off", also changed to Off as default like the real console.

### CODE REVIEW

**Comment by sorgelig** [comment]
I will change Transparency to Blend by default. This is more correct than supposed to be original way.
Originally it's supposed to be displayed on old low-quality CRT TV. Even more modern CRT TV and more common CRT Monitors are "too good" to provide visual blend effect, so it's not how it's supposed to be.
So, Blend is more correct emulation of low quality TV than original way.

**Comment by James-F2** [comment]
Well, I think same as with any other 'hack', the original output should be the default.
I would keep Off as default, but do as you think to be correct.

**Comment by sorgelig** [comment]
You are exaggerating CRT. Today most people use HDMI.

**Comment by James-F2** [comment]
In this retro gaming hobby, people who keep old heavy CRT know exactly why,, because a good CRT (Sony Trinitron for exmaple) produce fantastic lag-less, blur-free image with Scart RGB no LCD can simulate.

This 'pseudo blending' used in emulators is to simulate a 'bad' CRT with poor Composite input.
It is definitely a hack/filter that applied on top of the original signal, and probably should not be forced on people who do not know what it does.

**Comment by sorgelig** [comment]
MiSTer rule: HDMI first. VGA comes after and only if it doesn't contradicts HDMI features.

**Comment by James-F2** [comment]
Even if it creates undesirable artifacts and alters original signal?

**Comment by Kitrinx** [comment]
People should get the best experience by default. A lot more people play Kirby than Air Strike Patrol, and the lines are awful in that game. Most people using mister probably want blending on, and they can turn it off whenever they want.

**Comment by sorgelig** [comment]
Jurassic Park also has awful striped notification balloons when blending is off.

**Comment by James-F2** [comment]
Yes, Jurassic Park is especially bad.
That's the original signal and that's what I see with my real Snes and TV.

**Comment by Kitrinx** [comment]
also, air strike patrol (in case someone actually plays it) is not heavily impacted at all
aspmenu

**Comment by sorgelig** [comment]
I even don't see where artifacts are supposed to be

**Pull request merged**
