### PR TITLE
SNES Docs update & turbo mode test results/info page created

### PR DESCRIPTION
**Pull request by M-Walrus**
this is my first time using github and i accidentally created multiple commits instead of bundling all in one.
i know how to avoid doing this in the future, but i cannot find a way to remedy today's mistake in their web based editor currently.  apologies for this.

### CODE REVIEW

**Comment by sorgelig** [comment]
As i've mentioned in previous PR, i don't see the point of Turbo file. There are thousands of games, so this file is doomed to be orphaned. Turbo mode is kind of unsupported feature. There won't be any special work to improve or enhance it besides may be sporadic changes. 
I don't like the idea of this file with description of 0.001% games.

**Comment by M-Walrus** [comment]
Turbo file describes how the feature reacts only in games that are well known to have slowdown. not intended to cover everything out there, and i am willing to update it if changes are made as well.  the point of this doc is for people to get the most of this feature if they decide to use it, without having to fumble around and find out the hard way. 
This also warns users that this feature can cause issues, and lets them know they are to be expected.

**Comment by sorgelig** [comment]
Ok.
Let it be.
But please change X mark to something less confusing. X usually means "NO".

**Comment by M-Walrus** [comment]
thank you.

i can also add verbiage about this being an unsupported feature and not to report bugs with the feature enabled or expect any support on the feature outside of that document.

I will also change X to YES.  =)

**Pull request merged**
